# Workflow that creates artifacts of the latest dev versions.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: package

on:
    push:
        branches: [master]

jobs:
    package:
        name: Package applications
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 16.x
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@kieler'
            - run: yarn
            - run: yarn package
